image: topocourse
cache:
  paths:
    - .nb_output_cache

github mirror:
  stage: deploy
  script:
    - git push --mirror https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/topocm/topocm.git

upload_website:
  stage: deploy
  only:
    - master@qt/topocm
  script:
    - mkdir -p ~/.ssh && ssh-keyscan topocondmat.org >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - bash scripts/ipynb_to_html.sh
    - rm -rf ~/.ssh

edx_archive:
  script: ./scripts/converter.py --silent
  artifacts:
    paths:
      - generated/
    expire_in: 7d
    