image: topocourse
cache:
  paths:
    - .nb_output_cache

github mirror:
  script:
    - mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - git push --mirror git@github.com:topocm/topocm_content.git
    - rm -rf ~/.ssh

edx_archive:
  script: ./scripts/converter.py --silent
  artifacts:
    paths:
      - generated/
    expire_in: 7d

upload_website:
  stage: deploy
  only:
    - master@qt/topocm
  script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cd scripts && bash ipynb_to_html.sh && cd ..
    - "rsync -ravz generated/html/* topocm@tnw-tn1.tudelft.net:"
    - rm -rf ~/.ssh
    