image: topocourse
cache:
  paths:
    - .nb_output_cache
stages:
  - execute
  - deploy


execute_ipynbs:
  stage: execute
  script:
    - export PYTHONPATH=$PYTHONPATH:${PWD}/code
    - export DEST=generated/with_output
    - mkdir -p $DEST
    - cp syllabus.ipynb $DEST
    - cp -r data $DEST
    - cp -r w*_* $DEST
    - jupyter nbconvert --to notebook --inplace --config scripts/config_filter_smudge.py $DEST/**/*ipynb $DEST/syllabus.ipynb
    - rm -rf $DEST/data
  artifacts:
    paths:
      - generated/with_output
    expire_in: 7d


edx_archive:
  stage: deploy
  script: ./scripts/converter.py --silent ./generated/with_output
  artifacts:
    paths:
      - generated/import_to_edx.tar.gz
    expire_in: 7d


upload_test_website:
  stage: deploy
  only:
    - branches@qt/topocm
  except:
    - master@qt/topocm
  script:
    - export DEST=generated/html
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - python scripts/pelican_converter.py
    - pip install pelican markdown
    - pelican -o $DEST/ -s topocondmat/pelicanconf.py topocondmat/content/
    - "rsync -ravz --delete $DEST/* topocm-test@tnw-tn1.tudelft.net:"
    - rm -rf ~/.ssh


upload_website:
  stage: deploy
  only:
    - master@qt/topocm
  script:
    - export DEST=generated/html
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - cp -r generated/with_output $DEST
    - jupyter nbconvert --to html --Exporter.preprocessors=[\"scripts.htmllinks.HtmlLinksPreprocessor\"] --template scripts/website_template.tpl $DEST/**/*.ipynb $DEST/syllabus.ipynb
    - rm $DEST/**/*.ipynb $DEST/syllabus.ipynb
    - "rsync -ravz --delete $DEST/* topocm@tnw-tn1.tudelft.net:"
    - rm -rf ~/.ssh
