image: topocourse
cache:
  paths:
    - .nb_output_cache

execute_ipynbs:
  stage: build
  script:
    - export PYTHONPATH=$PYTHONPATH:${PWD}/code
    - export DEST=generated/with_output
    - mkdir -p $DEST
    - cp syllabus.ipynb $DEST
    - cp -r data $DEST
    - cp -r w*_* $DEST
    - jupyter nbconvert --to notebook --inplace --config scripts/config_filter_smudge.py $DEST/**/*ipynb
    - rm -rf $DEST/data
  artifacts:
    paths:
      - generated/with_output
    expire_in: 7d

edx_archive:
  script: ./scripts/converter.py --silent
  artifacts:
    paths:
      - generated/import_to_edx.tar.gz
    expire_in: 7d

upload_test_website:
  stage: deploy
  only:
    - branches@qt/topocm
  except:
    - master@qt/topocm
  script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - python scripts/ipynb_to_html.py
    - "rsync -ravz --delete generated/html/* topocm-test@tnw-tn1.tudelft.net:"
    - rm -rf ~/.ssh


upload_website:
  stage: deploy
  only:
    - master@qt/topocm
  script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - python scripts/ipynb_to_html.py
    - "rsync -ravz --delete generated/html/* topocm@tnw-tn1.tudelft.net:"
    - rm -rf ~/.ssh
